# ─────────────────────────────────────────
#  이메일(SMTP) 설정
# ─────────────────────────────────────────
mail.smtp.host=mw-002.cafe24.com
mail.smtp.port=587
mail.smtp.username=lottorank@lottorank.co.kr
mail.smtp.password=tkfkdgo!@
mail.from=lottorank@lottorank.co.kr
